// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKK_ojDmnT0vE-8Hh-W7h4qK20aDWB_IQ',
    appId: '1:1074466000841:web:20af6d4696dd20e49b2218',
    messagingSenderId: '1074466000841',
    projectId: 'emolearn-app-25f5b',
    authDomain: 'emolearn-app-25f5b.firebaseapp.com',
    storageBucket: 'emolearn-app-25f5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMG_YDzPtDyqEpyuv3uWNWGPQVix_oY08',
    appId: '1:1074466000841:android:5a047e383998dae09b2218',
    messagingSenderId: '1074466000841',
    projectId: 'emolearn-app-25f5b',
    storageBucket: 'emolearn-app-25f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhiA1StNei9fLJG1pV92Sf53MSPOuCRoc',
    appId: '1:1074466000841:ios:bfaea880face145c9b2218',
    messagingSenderId: '1074466000841',
    projectId: 'emolearn-app-25f5b',
    storageBucket: 'emolearn-app-25f5b.appspot.com',
    iosClientId: '1074466000841-5momm7476en0ndctrkni0999o4i771l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.onBoarding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhiA1StNei9fLJG1pV92Sf53MSPOuCRoc',
    appId: '1:1074466000841:ios:bfaea880face145c9b2218',
    messagingSenderId: '1074466000841',
    projectId: 'emolearn-app-25f5b',
    storageBucket: 'emolearn-app-25f5b.appspot.com',
    iosClientId: '1074466000841-5momm7476en0ndctrkni0999o4i771l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.onBoarding',
  );
}
